common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

from pybo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

pybo/urls.py
from django.urls import path

from . import views

app_name = 'pybo'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

common/models.py
from django.db import models

# Create your models here.

pybo/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

pybo/forms.py
from django import forms
from pybo.models import Question, Answer


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question  # 사용할 모델
        fields = ['subject', 'content']  # QuestionForm에서 사용할 Question 모델의 속성
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }

common/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib.sessions.backends.db import SessionStore


def index(request):
    ...
    # 방법 1
    s = SessionStore()
    s['key'] = 'value'
    s.create()

    # 방법 2
    request.session['key'] = value
    ...
    return render(request, 'index.html')

pybo/views.py
from django.http import HttpResponse  # 삭제
from django.shortcuts import render, get_object_or_404, redirect
from .models import Question, Answer
from django.utils import timezone
from .forms import QuestionForm, AnswerForm
from django.contrib.auth.decorators import login_required

from django.http import HttpResponseNotAllowed

@login_required
def index(request):
    question_list = Question.objects.order_by('-create_date')
    context = {'question_list': question_list}
    return render(request, 'pybo/question_list.html', context)
#pybo/question_list.html
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.answer_set.create(content=request.POST.get('content'), create_date=timezone.now())
    return redirect('pybo:detail', question_id=question.id)

def answer_create(request, question_id):
    """
    pybo 답변등록
    """
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        return HttpResponseNotAllowed('Only POST is possible.')
    context = {'question': question, 'form': form}
    return render(request, 'pybo/question_detail.html', context)

def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>파이보!</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/base_login.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'sb-admin-2.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'sb-admin-2.min.css' %}">
    <title>Konnect</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'login.js' %}"></script>
</body>
</html>

templates/common/login.html
{% extends "base_login.html" %}
{% block content %}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Konnect</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <style>
	    body{color:black;}
	    #wrapper{background-color:white; margin:0.5%;}
	    #wrapper #content-wrapper{background-color:white;}
	    .card-header{background-color:white;}
    </style>

</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->

                   	<!-- Content Row -->
                    <div class="row">
                        <div class="col-lg-3" style="margin: auto;">
                        	<div class="">
                        		<div class="card-header">
                                    <h4 class="m-1 font-weight-bold" style="text-align:center">Log in</h4>
                                </div>
                        		<div class="card-body">
                                    <div class="row align-items-center">
                                        <div class="col mr-2">
                                            <form method="post" action="{% url 'common:login' %}">
                                                {% csrf_token %}
                                                {% include "form_errors.html" %}
                                                <div class="social-container">
                                                    <input type="text" class="form-control" name="username" id="username"
                                                           value="{{ form.username.value|default_if_none:'' }}" placeholder="ID">
                                                </div><br>
                                                <div class="social-container">
                                                    <input type="password" class="form-control" name="password" id="password"
                                                           value="{{ form.password.value|default_if_none:'' }}" placeholder="Password">
                                                </div><br>
                                                <div style="text-align:center">
                                                <button type="submit" class="btn btn-primary" >로그인</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                        	</div>
                        </div>
                    </div>
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
</body>
</html>

{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
{%load static%}

<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">
            <img style="width:150px" src="{% static '/Konnect_BI.png' %}"></a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    <a class="nav-link" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                    <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/pybo/main.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Yaksonhc Dashboard</title>

    <!-- Custom fonts for this template-->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="css/sb-admin-2.min.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    
    <style>
	    body{color:black;}
	    #wrapper{background-color:white; margin:5%;}
	    #wrapper #content-wrapper{background-color:white;}
	    .card-header{background-color:white;}
    </style>
    
</head>

<body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="card-header">
                        <h5 class="h3 mb-0 text-gray-800">마인드호 탑승 안내서</h5>
                    </div>

                   	<!-- Content Row -->
                    <div class="row">
                        <div class="col-lg-3">
                        	<div class="">
                        		<div class="card-header">
                                    <h2 class="m-1 font-weight-bold">1. 회사소개</h2>
                                </div>
                        		<div class="card-body">
                                    <div class="row align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> &#128539; 마인드리퍼블릭은? </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 미션과 비젼 [2023] </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 내부 소개 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 지문인식 출입시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 취업규칙 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 주차 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 오시는길 안내 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 손님응대 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 물류센터 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 승진시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 연봉체계 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 자주 물어보는 질문 (FAQ) </div><br>
                                        </div>
                                    </div>
                                </div>
                        	</div>
                        </div> 
                        <div class="col-lg-3">
                        	<div class="">
                        		<div class="card-header">
                                    <h2 class="m-1 font-weight-bold">2. 문화복지</h2>
                                </div>
                        		<div class="card-body">
                                    <div class="row align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 마인드리퍼블릭은? </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 미션과 비젼 [2023] </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 내부 소개 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 지문인식 출입시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 취업규칙 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 주차 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 오시는길 안내 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 손님응대 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 물류센터 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 승진시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 연봉체계 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 자주 물어보는 질문 (FAQ) </div><br>
                                        </div>
                                    </div>
                                </div>
                        	</div>
                        </div> 
                        <div class="col-lg-3">
                        	<div class="">
                        		<div class="card-header">
                                    <h2 class="m-1 font-weight-bold">3. 업무 TOOL</h2>
                                </div>
                        		<div class="card-body">
                                    <div class="row align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 마인드리퍼블릭은? </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 미션과 비젼 [2023] </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 내부 소개 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 지문인식 출입시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 취업규칙 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 주차 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 오시는길 안내 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 손님응대 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 물류센터 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 승진시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 연봉체계 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 자주 물어보는 질문 (FAQ) </div><br>
                                        </div>
                                    </div>
                                </div>
                        	</div>
                        </div> 
                        <div class="col-lg-3">
                        	<div class="">
                        		<div class="card-header">
                                    <h2 class="m-1 font-weight-bold">4. 서포트</h2>
                                </div>
                        		<div class="card-body">
                                    <div class="row align-items-center">
                                        <div class="col mr-2">
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 마인드리퍼블릭은? </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 미션과 비젼 [2023] </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 내부 소개 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 지문인식 출입시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 취업규칙 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 사무실 주차 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 오시는길 안내 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 손님응대 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 물류센터 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 승진시스템 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 연봉체계 </div><br>
                                            <div class="text-lg font-weight-bold text-uppercase mb-1"> 자주 물어보는 질문 (FAQ) </div><br>
                                        </div>
                                    </div>
                                </div>
                        	</div>
                        </div> 
                    </div>                    
                </div>
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
</body>
</html>

templates/pybo/question_detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container my-3">
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'pybo:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>

{% endblock %}

templates/pybo/question_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
            {% for field in form %}
            {% if field.errors %}
            <div>
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
            </div>
            {% endif %}
            {% endfor %}
        </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="mb-3">
            <label for="subject" class="form-label">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="content" class="form-label">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}